const fs = require('fs');

// course id -> {domain, name} from the hub APPS
const hub = fs.readFileSync('index.html', 'utf8');
const disc = {};
const re = /id: '([a-z]+)', name: '([^']*)', domain: '([a-z]+)'/g;
let m;
while ((m = re.exec(hub)) !== null) disc[m[1]] = { name: m[2], domain: m[3] };

const files = fs.readdirSync('.').filter(f => f.endsWith('.html') && f !== 'index.html').sort();
const cards = [];
const index = [];
const problems = [];

files.forEach(f => {
  const id = f.replace('.html', '');
  const text = fs.readFileSync(f, 'utf8');
  const km = text.match(/const STORAGE_KEY\s*=\s*'([^']+)'/);
  const cm = text.match(/const CARDS\s*=\s*(\[[\s\S]*?\n\]);/);
  if (!km || !cm) { problems.push(f + ' (key=' + !!km + ' cards=' + !!cm + ')'); return; }
  const key = km[1];
  let arr;
  try { arr = eval('(' + cm[1] + ')'); }
  catch (e) { problems.push(f + ' eval: ' + e.message); return; }
  const d = (disc[id] && disc[id].domain) || 'unknown';
  const name = (disc[id] && disc[id].name) || id.toUpperCase();
  arr.forEach(c => {
    cards.push({ course: id, key: key, disc: d, id: c.id, core: !!c.core, front: c.front, back: c.back });
  });
  index.push({ course: id, key: key, disc: d, name: name, count: arr.length });
});

if (problems.length) { console.error('PROBLEMS:\n  ' + problems.join('\n  ')); process.exit(1); }

const head = '/* AUTO-GENERATED by scripts/gen-review.js from the 50 course CARDS arrays. Do not edit by hand. */\n';
fs.writeFileSync('review-cards.js', head + 'window.REVIEW_CARDS = [\n' + cards.map(c => JSON.stringify(c)).join(',\n') + '\n];\n');
fs.writeFileSync('review-index.js', head + 'window.REVIEW_INDEX = [\n' + index.map(c => JSON.stringify(c)).join(',\n') + '\n];\n');

console.log('courses:', index.length, '| cards:', cards.length);
console.log('review-cards.js:', (fs.statSync('review-cards.js').size / 1024).toFixed(0) + ' KB');
console.log('review-index.js:', (fs.statSync('review-index.js').size) + ' B');
// distinct disciplines present
console.log('disciplines:', [...new Set(index.map(i => i.disc))].join(', '));
